### ISSUE TITLE
Fullscreen youtube video on firefox doesn't work

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#110] opened 2020-05-15 14:02 UTC
If I watch a video using firefox (youtube or dailymotion) and click the full screen button then firefox becomes fullscreen, same as F11 shortcut, but it's not the video that is fullscreen

**Comment by ItzSwirlz** [comment] 2020-09-30 02:37
Other games with firefox are similar to this.

I think the problem is-the panel/widget should be autohiding some stuff-or needs more customization settings such as width and such.

But I'm new and am introducing myself to Fyne so /shrug

**Comment by andydotxyz** [comment] 2020-10-23 11:04
This is a gnarly bug. It seems that somehow FireFox is not completing fullscreen mode correct.
Once we fix that glitch it should not matter that we have widgets on the desktop etc as it will draw an overlay like Chromium does.

**Comment by andydotxyz** [comment] 2021-01-29 11:51
Fixed on develop

**Closed by andydotxyz** 2021-01-29 11:51 UTC
Labels: Hacktoberfest, blocker, bug
